### ISSUE TITLE
Bug on resource that is not deployed after some errors

### ISSUE THREAD

**Issue by irainia** [odpf/optimus#547] opened 2022-08-30 03:57 UTC
**Describe the bug**

This bug happens when there's a failure when deploying resource into its service provider, such as bigquery. The steps below should explain better about this case.

**To Reproduce**
1. create a valid resource, such as view. however, make sure that the resource will be failed when storing to the service provider, like bigquery. for example like access.
2. deploy to optimus the newly created resource. in this state, optimus should fail the deployment process to the service provider. however, the resource itself is already stored in the database.
3. don't update the resource spec, just update the access for it to pass the service provider
4. re-deploy through optimus. and in this step, optimus shouldn't fail. however, optimus will skip deployment process, meaning the resource is not created.

The reason for the result of the steps above is because in Optimus, we have a mechanism to skip resource if there is no difference between the incoming one and the one in database.

**Expected behavior**
Resource should be stored in database, and deployed to the targetted service provider.

**Comment by sravankorumilli** [comment] 2022-09-09 11:01
Duplicate of #533

**Closed** 2022-09-09 11:01 UTC
Labels: bug

**Comment by deryrahman** [comment] 2022-09-19 07:27
@irainia @sravankorumilli the problem of this issue is because there's lack of atomicity in our create / update resource system. Atomicity means all or nothing. In this case, there're 2 main operation in create / update resource (in sequential order):

1. save the resource spec to DB
2. actual table creation / modification on service provider

When atomicity is not provided, for example, whenever access on service provider is problematic, only the first operation is getting executed and the second operation is **not** being executed. We need a mechanism where if one of both operation is failing, then all operation is not executed.

So far the approach we can take is rolling back when one operation is failing. eg, when actual table creation / modification is failing, then, resource spec in DB should be rolled back to the previous state.
